Remove dependency, update version #
* dependency does not work on Windows for some reason

* version # of http-proxy was old, and "node server.js" would produce the following error:

util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (d:\src\cors-anywhere\node_modules\http-proxy\lib\http-proxy\index.js:108:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\src\cors-anywhere\node_modules\http-proxy\lib\http-proxy.js:4:17)